### ISSUE TITLE
Add multiple Audio file.

### ISSUE THREAD

**Issue by pratik1311** [cf-L/SlideShowMaker#5]
Hello,

Thanks for providing such a great library for SlideShow. 

In my app requirement I have to add multiple audio files. 
Can you please guide me how can I do that?

Thanks
Pratik

**Comment by cf-L** [comment]
@pratik1311

**Comment by cf-L** [comment]
Hi @pratik1311 

Thanks for using this pod !

1. If you want play multiple audio files at one time, you may create multiple audio track like [this](https://github.com/cf-L/SlideShowMaker/blob/9e1fc14f8e60a64fc61dfbb50bc63af6707e183b/SlideShowMaker/Classes/VideoExporter.swift#L88)

2. If you want play multiple audio files at one audio track, you may control the time range for playing audio files one by one, like [this](https://github.com/cf-L/SlideShowMaker/blob/9e1fc14f8e60a64fc61dfbb50bc63af6707e183b/SlideShowMaker/Classes/VideoExporter.swift#L100)

Hope this helps.

By the way, I would create another better pod for SlideShow.
